name: 发布NPM包

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v3

    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: 安装依赖
      run: npm install

    - name: 凹凸版本和发布
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm install semver

        current_version=$(node -p "require('./package.json').version")
        echo "当前版本: $current_version"

        new_version=$(node -p "require('semver').inc('$current_version', 'patch')")
        echo "新版本: $new_version"

        npm version $new_version --no-git-tag-version
        
        npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        
        npm publish

- name: 推送新版本标签
  if: success()
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git commit -am "$new_version"
    git tag $new_version
    git push origin main --tags